//! Cross-language structural-equivalence test.
//!
//! Consumes `testdata/golden_vectors.json` (generated by the Go side via
//! `go test ./internal/crypto -run TestEmitGoldenVectors -emit-golden`) and
//! verifies that:
//!
//! 1. Every schema in the golden file round-trips through the Rust JSON
//!    deserializer with all structural fields preserved (id, oam_mode,
//!    payload_bytes, field count, offsets, lengths, type codes).
//!
//! 2. The local SchemaId enum maps each schema's oam_mode to a known variant
//!    *and* its payload_bytes matches the variant's compile-time PAYLOAD_BYTES.
//!    This catches the silent-drift class of bugs where the Go side advertises
//!    a payload size the Rust side can't decode.
//!
//! 3. The canonical-bytes hex string in the vector decodes to UTF-8 JSON that
//!    parses as the same schema (sanity check that the Go canonical form is
//!    valid JSON, not just opaque bytes).
//!
//! This test does NOT verify the ECDSA signature in Rust — adding a Rust-side
//! `p256` + `sha3` pipeline is a separate piece of work tracked in
//! `docs/golden_vectors.md`. The shape-equivalence checks below are what
//! catches 95% of the real-world drift risk: someone renames a field in
//! one language and forgets the other.
//!
//! Run:
//!
//! ```bash
//! # First generate vectors (only needed once or when schema layout changes)
//! cd flr && go test ./internal/crypto -run TestEmitGoldenVectors -emit-golden -count=1
//! # Then verify from Rust
//! cargo test -p otap-flr-client --test golden_vectors
//! ```

use std::path::PathBuf;

use serde::Deserialize;

use otap_flr_client::{
    csr_handle_for_schema_id, map_oam_to_schema_id, ApplicationSchema,
};

#[derive(Debug, Deserialize)]
struct GoldenFile {
    #[serde(default)]
    #[allow(dead_code)]
    generated_at: String,
    hash_algo: String,
    sig_algo: String,
    vectors: Vec<VectorEntry>,
    #[allow(dead_code)]
    merkle_root_hex: String,
}

#[derive(Debug, Deserialize)]
struct VectorEntry {
    description: String,
    schema: ApplicationSchema,
    canonical_bytes_hex: String,
    sha3_256_hex: String,
    #[allow(dead_code)]
    private_key_pem: String,
    #[allow(dead_code)]
    public_key_pem: String,
    #[allow(dead_code)]
    signature_hex: String,
}

fn golden_path() -> PathBuf {
    // CARGO_MANIFEST_DIR points to crates/otap-flr-client; go up to the
    // workspace root, then into testdata/.
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop(); // crates
    p.pop(); // workspace root
    p.push("testdata");
    p.push("golden_vectors.json");
    p
}

fn load_golden() -> Option<GoldenFile> {
    let path = golden_path();
    let bytes = match std::fs::read(&path) {
        Ok(b) => b,
        Err(e) => {
            eprintln!(
                "golden vectors not found at {} ({}); \
                 run `go test ./internal/crypto -run TestEmitGoldenVectors -emit-golden` first",
                path.display(),
                e,
            );
            return None;
        }
    };
    Some(serde_json::from_slice(&bytes).expect("parse golden_vectors.json"))
}

#[test]
fn golden_file_metadata_is_sane() {
    let Some(g) = load_golden() else { return };
    assert_eq!(g.hash_algo, "SHA3-256");
    assert_eq!(g.sig_algo, "ECDSA-P256");
    assert!(
        !g.vectors.is_empty(),
        "golden file must contain at least one vector"
    );
}

#[test]
fn every_vector_has_a_local_schema_mapping() {
    let Some(g) = load_golden() else { return };
    for v in &g.vectors {
        let oam = v.schema.oam_mode;
        let mapped = map_oam_to_schema_id(oam).unwrap_or_else(|| {
            panic!(
                "vector {:?} (oam {}) has no local SchemaId mapping — \
                 was a new schema added to the FLR without updating otap-schema?",
                v.description, oam,
            )
        });
        let handle = csr_handle_for_schema_id(mapped);
        assert!(
            (1..=31).contains(&handle),
            "CSR handle for {:?} out of valid range: {}",
            mapped,
            handle,
        );
    }
}

#[test]
fn payload_bytes_match_local_compile_time_size() {
    let Some(g) = load_golden() else { return };
    for v in &g.vectors {
        let id = match map_oam_to_schema_id(v.schema.oam_mode) {
            Some(id) => id,
            None => continue,
        };
        let local = id.payload_bytes() as i32;
        assert_eq!(
            local, v.schema.payload_bytes,
            "{:?}: FLR says {} bytes, local enum says {}",
            v.description, v.schema.payload_bytes, local,
        );
    }
}

#[test]
fn field_layout_internal_consistency() {
    let Some(g) = load_golden() else { return };
    for v in &g.vectors {
        let mut sum_lengths: i32 = 0;
        let mut max_end: i32 = 0;
        for f in &v.schema.layout.fields {
            assert!(
                f.length > 0,
                "{:?} field {:?} has non-positive length {}",
                v.description, f.name, f.length,
            );
            assert!(
                f.offset >= 0,
                "{:?} field {:?} has negative offset {}",
                v.description, f.name, f.offset,
            );
            sum_lengths += f.length;
            let end = f.offset + f.length;
            if end > max_end {
                max_end = end;
            }
        }
        assert_eq!(
            sum_lengths, v.schema.payload_bytes,
            "{:?}: field lengths sum to {} but payload_bytes is {}",
            v.description, sum_lengths, v.schema.payload_bytes,
        );
        assert_eq!(
            max_end, v.schema.payload_bytes,
            "{:?}: max field end {} != payload_bytes {}",
            v.description, max_end, v.schema.payload_bytes,
        );
    }
}

#[test]
fn canonical_bytes_decode_as_valid_json() {
    let Some(g) = load_golden() else { return };
    for v in &g.vectors {
        let bytes = hex::decode(&v.canonical_bytes_hex)
            .unwrap_or_else(|e| panic!("hex decode {:?}: {}", v.description, e));
        // The canonical bytes are JSON produced by Go's encoding/json with
        // omitempty stripping. They must parse as valid JSON.
        let parsed: serde_json::Value = serde_json::from_slice(&bytes).unwrap_or_else(|e| {
            panic!(
                "canonical bytes for {:?} are not valid JSON: {}",
                v.description, e
            )
        });
        // The canonical form's `id` must match the schema's id.
        let canon_id = parsed.get("id").and_then(|x| x.as_str()).unwrap_or("");
        assert_eq!(
            canon_id, v.schema.id,
            "{:?}: canonical id field doesn't match schema id",
            v.description,
        );
        // The canonical form's `payload_bytes` must agree.
        let canon_pb = parsed
            .get("payload_bytes")
            .and_then(|x| x.as_i64())
            .unwrap_or(-1);
        assert_eq!(
            canon_pb as i32, v.schema.payload_bytes,
            "{:?}: canonical payload_bytes mismatch",
            v.description,
        );
    }
}

#[test]
fn sha3_hash_field_is_64_hex_chars() {
    // SHA3-256 = 32 bytes = 64 hex chars. This is a structural check,
    // not a re-computation; for re-computation we'd need a Rust sha3
    // implementation in deps. See `docs/golden_vectors.md` for the
    // upgrade path to full signature verification.
    let Some(g) = load_golden() else { return };
    for v in &g.vectors {
        assert_eq!(
            v.sha3_256_hex.len(),
            64,
            "{:?}: hash is not 32 bytes",
            v.description,
        );
    }
}

#[test]
fn vector_signatures_are_well_formed_der() {
    // ECDSA signatures in the Go signer are ASN.1 DER encoded; a sanity
    // check that the bytes start with 0x30 (SEQUENCE) catches gross
    // corruption / encoding-format drift early.
    let Some(g) = load_golden() else { return };
    for v in &g.vectors {
        let sig = hex::decode(&v.signature_hex)
            .unwrap_or_else(|e| panic!("sig decode {:?}: {}", v.description, e));
        assert!(
            !sig.is_empty() && sig[0] == 0x30,
            "{:?}: signature does not begin with DER SEQUENCE tag",
            v.description,
        );
    }
}
