//! GF(1024) = GF(2^10) tables for Reed-Solomon FEC over the Lux codebook.
//!
//! Field defined by the primitive polynomial x^10 + x^3 + 1 (0x409).
//! Built at Zig comptime — exp/log arrays and the RS generator polynomial
//! live in .rodata of the consuming Rust crate with zero initialization
//! cost at runtime.
//!
//! Building: `zig run zig/gf1024.zig > crates/otap-luxcode/src/gf1024.rs`
//! or use the orchestrating `make zig-codegen` target.

const std = @import("std");

// --- Field parameters ------------------------------------------------------

const FIELD_BITS: u8 = 10;
const ORDER: u16 = 1 << FIELD_BITS; // 1024
const NONZERO: u16 = ORDER - 1; // 1023

/// Primitive polynomial: x^10 + x^3 + 1 = 0x409.
const PRIM_POLY: u16 = 0x409;

/// Number of RS parity symbols (16 symbol corrections via Berlekamp-Massey
/// over a syndrome polynomial of degree 16).
const RS_PARITY: u8 = 16;

// --- Comptime table construction -------------------------------------------

const Tables = struct {
    /// exp[i] = α^i for i in [0, NONZERO); exp[NONZERO] = exp[0] = 1 wraps.
    exp: [ORDER]u16,
    /// log[α^i] = i; log[0] is a sentinel (never used for x = 0).
    log: [ORDER]u16,
    /// Generator polynomial coefficients, low-to-high degree.
    /// g(x) = ∏_{i=0}^{RS_PARITY-1} (x − α^i).
    generator: [RS_PARITY + 1]u16,
};

fn gfMulRuntime(a: u16, b: u16, exp: []const u16, log: []const u16) u16 {
    if (a == 0 or b == 0) return 0;
    const sum: u32 = @as(u32, log[a]) + @as(u32, log[b]);
    return exp[@intCast(sum % NONZERO)];
}

const tables: Tables = blk: {
    @setEvalBranchQuota(2_000_000);
    var t: Tables = undefined;

    // Build exp/log via the α generator.
    var x: u16 = 1;
    var i: u16 = 0;
    while (i < NONZERO) : (i += 1) {
        t.exp[i] = x;
        t.log[x] = i;
        x <<= 1;
        if ((x & ORDER) != 0) {
            x ^= PRIM_POLY;
        }
        x &= NONZERO;
    }
    t.exp[NONZERO] = 1; // α^NONZERO == α^0
    t.log[0] = 0; // sentinel — must not be relied on

    // RS generator polynomial: ∏(x − α^j) for j in [0, RS_PARITY).
    var gen = [_]u16{0} ** (RS_PARITY + 1);
    gen[0] = 1;
    var len: usize = 1;
    var k: u16 = 0;
    while (k < RS_PARITY) : (k += 1) {
        const alpha_k = t.exp[k];
        // Multiply gen(x) by (x + α^k) (XOR-add in GF(2)).
        var next = [_]u16{0} ** (RS_PARITY + 1);
        var j: usize = 0;
        while (j <= len) : (j += 1) {
            if (j > 0) next[j] ^= gen[j - 1];
            if (j < len) next[j] ^= gfMulRuntime(gen[j], alpha_k, &t.exp, &t.log);
        }
        gen = next;
        len += 1;
    }
    t.generator = gen;
    break :blk t;
};

// --- Multiplication-by-α^j matrices for bit-sliced arithmetic ----------------
//
// Bit-sliced GF(2^10) decomposes each field element into 10 separate bit
// planes (one plane per bit position, holding that bit across many codewords).
// Multiplication by a *constant* α^j is then a linear GF(2) transformation on
// the planes: out[k] = XOR over { in[i] : M_{α^j}[k][i] == 1 }.
//
// We precompute the 10×10 binary matrix for each α^j we care about (the 16
// RS roots) and emit it as a Rust `[[u16; 10]; 16]`. Each row mask has 10
// bits packed into a u16: bit i tells whether input plane i contributes to
// output plane k.

const NUM_MUL_MATRICES: usize = 16;
const MulMatrix = [10]u16;

fn gfMul(a: u16, b: u16) u16 {
    if (a == 0 or b == 0) return 0;
    const sum: u32 = @as(u32, tables.log[a]) + @as(u32, tables.log[b]);
    return tables.exp[@intCast(sum % NONZERO)];
}

fn buildMulMatrix(alpha: u16) MulMatrix {
    var m: MulMatrix = [_]u16{0} ** 10;
    var i: u8 = 0;
    while (i < 10) : (i += 1) {
        const e_i: u16 = @as(u16, 1) << @intCast(i);
        const prod = gfMul(e_i, alpha);
        var k: u8 = 0;
        while (k < 10) : (k += 1) {
            if ((prod >> @intCast(k)) & 1 != 0) {
                m[k] |= @as(u16, 1) << @intCast(i);
            }
        }
    }
    return m;
}

const mul_matrices: [NUM_MUL_MATRICES]MulMatrix = blk: {
    @setEvalBranchQuota(2_000_000);
    var arr: [NUM_MUL_MATRICES]MulMatrix = undefined;
    var j: usize = 0;
    while (j < NUM_MUL_MATRICES) : (j += 1) {
        arr[j] = buildMulMatrix(tables.exp[j]);
    }
    break :blk arr;
};

// --- Rust emitter ----------------------------------------------------------

pub fn main() !void {
    const out = std.io.getStdOut().writer();

    try out.print(
        \\// Generated by zig/gf1024.zig. DO NOT EDIT.
        \\//
        \\// GF(1024) = GF(2^10) tables for Reed-Solomon FEC over the Lux codebook.
        \\// Primitive polynomial: x^10 + x^3 + 1 (0x409).
        \\// Generator: {[parity]d} parity symbols, {[gen_len]d} coefficients.
        \\//
        \\// All tables built at Zig comptime; this file is .rodata at runtime.
        \\// Regenerate with `make zig-codegen`.
        \\
        \\#![allow(dead_code)]
        \\
        \\pub const GF1024_FIELD_BITS: u8 = {[bits]d};
        \\pub const GF1024_ORDER: u16 = {[order]d};
        \\pub const GF1024_NONZERO: u16 = {[nonzero]d};
        \\pub const GF1024_PRIM_POLY: u16 = 0x{[prim]X};
        \\pub const RS_PARITY_LEN: usize = {[parity]d};
        \\
        \\
    , .{
        .bits = FIELD_BITS,
        .order = ORDER,
        .nonzero = NONZERO,
        .prim = PRIM_POLY,
        .parity = RS_PARITY,
        .gen_len = RS_PARITY + 1,
    });

    try emitU16Array(out, "GF1024_EXP", tables.exp[0..]);
    try emitU16Array(out, "GF1024_LOG", tables.log[0..]);
    try emitU16Array(out, "RS_GENERATOR", tables.generator[0..]);

    // u32-widened mirrors used by the AVX2 syndrome evaluator. The gather
    // intrinsic only supports 32- or 64-bit elements, so we need the same
    // values padded to u32 for VPGATHERDD.
    try emitU32Mirror(out, "GF1024_EXP_U32", tables.exp[0..]);
    try emitU32Mirror(out, "GF1024_LOG_U32", tables.log[0..]);

    // Multiplication-by-α^j matrices for the bit-sliced evaluator.
    try out.print(
        \\/// Multiplication-by-α^j matrices for bit-sliced GF(2^10) arithmetic.
        \\///
        \\/// `MUL_BY_ALPHA[j][k]` is a 10-bit mask: bit `i` is set iff the bit-i
        \\/// plane of the input contributes to the bit-k plane of the output when
        \\/// the value is multiplied by α^j in GF(2^10) (primitive polynomial
        \\/// x^10 + x^3 + 1). Used by `crate::bitsliced::rs_syndromes_bitsliced`.
        \\pub const MUL_BY_ALPHA: [[u16; 10]; {[n]d}] = [
        \\
    , .{ .n = NUM_MUL_MATRICES });
    for (mul_matrices, 0..) |m, j| {
        try out.print("    // α^{d}\n    [", .{j});
        for (m, 0..) |row, k| {
            try out.print("0x{X:0>3}", .{row});
            if (k + 1 < m.len) try out.print(", ", .{});
        }
        try out.print("],\n", .{});
    }
    try out.print("];\n", .{});
}

fn emitU32Mirror(out: anytype, name: []const u8, arr: []const u16) !void {
    try out.print("pub const {s}: [u32; {d}] = [\n", .{ name, arr.len });
    var i: usize = 0;
    while (i < arr.len) : (i += 1) {
        if (i % 8 == 0) try out.print("    ", .{});
        try out.print("0x{X:0>3},", .{arr[i]});
        if ((i + 1) % 8 == 0 or i + 1 == arr.len) {
            try out.print("\n", .{});
        } else {
            try out.print(" ", .{});
        }
    }
    try out.print("];\n\n", .{});
}

fn emitU16Array(out: anytype, name: []const u8, arr: []const u16) !void {
    try out.print("pub const {s}: [u16; {d}] = [\n", .{ name, arr.len });
    var i: usize = 0;
    while (i < arr.len) : (i += 1) {
        if (i % 8 == 0) try out.print("    ", .{});
        try out.print("0x{X:0>3},", .{arr[i]});
        if ((i + 1) % 8 == 0 or i + 1 == arr.len) {
            try out.print("\n", .{});
        } else {
            try out.print(" ", .{});
        }
    }
    try out.print("];\n\n", .{});
}
