// Code generated by avo. DO NOT EDIT.
// Stub declarations for AVX-512 bit-woven conflict detection.
// The actual assembly is generated by running: go run ./avo/gen.go -out bitweave_avx512.s

//go:build amd64 && avx512

package bitweave

// matchAttribute32AVX512 evaluates a 32-bit attribute match across 1024 leases
// using AVX-512 AND/ANDNOT operations on bit-planes.
// Processes 512 leases per ZMM register, 2 registers per plane = 1024 leases total.
//
//go:noescape
func matchAttribute32AVX512(planes *[32][wordsPerPlane]uint64, activeMask *[wordsPerPlane]uint64, target uint32, result *[wordsPerPlane]uint64)

// matchAttribute16AVX512 evaluates a 16-bit attribute match across 1024 leases
// using AVX-512 AND/ANDNOT operations on bit-planes.
//
//go:noescape
func matchAttribute16AVX512(planes *[16][wordsPerPlane]uint64, activeMask *[wordsPerPlane]uint64, target uint16, result *[wordsPerPlane]uint64)

// combineConflictsAVX512 combines per-attribute match masks into final
// conflict masks (lambda collision, port collision, tenant isolation).
//
// lambdaConflict  = channelMatch & awgMatch & exclusiveMask
// portConflict    = awgMatch & portMatch
// tenantConflict  = channelMatch & awgMatch & ~tenantMatch
//
//go:noescape
func combineConflictsAVX512(channelMatch, awgMatch, portMatch, tenantMatch, exclusiveMask, lambdaOut, portOut, tenantOut *[wordsPerPlane]uint64)

// popcount1024AVX512 counts the total number of set bits in a 1024-bit mask
// using scalar POPCNTQ across 16 words.
//
//go:noescape
func popcount1024AVX512(mask *[wordsPerPlane]uint64) uint64
